### ISSUE TITLE
White & grey streaks screen on twrp boot

### ISSUE THREAD

**Issue by wonderfullyrich** [chaosmaster/android_device_fairphone_fp3#2]
Just pulled twrp-3.3.1-0_k4y0z-20200202-02-fp3.img and did a fastboot boot twrp-3.3.1-0_k4y0z-20200202-02-fp3.img 
Done on a macos using 
fastboot version 29.0.5-5949299
Installed as /usr/local/bin/fastboot

results in 
Sending 'boot.img' (28690 KB)                      OKAY [  0.644s]
Booting                                            OKAY [  8.662s]
Finished. Total time: 9.392s

However when it boots, I get a white screen with grey streaks that shift around.  Guessing it looks like a video output format issue, but I've not seen this on an Android TWRP before.

I'm able to do a long press power down and reboot it back into the OS, but only after a bit of repetition.

**Comment by chaosmaster** [comment]
Is your device a Fairphone 3?
Do you have adb access when it shows like that?
Try redownloading the file.
I haven't seen this issue before.

**Comment by wonderfullyrich** [comment]
Correct, brand new fairphone 3.

I do have adb access, however if I do a 'adb reboot bootloader' as an example, the screen remains white with grey streaks. (The grey streaks roam across the horizontal.)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chaosmaster** [comment]
What firmware-version is installed?

**Comment by wonderfullyrich** [comment]
-------- Original Message --------

**Comment by smurfix** [comment]
I got this effect too, the first two or three times I booted with TWRP. The third time I pushed the power button twice, and when it woke up the normal TWRP screen was visible. After that, the problem disappeared, I can now boot into TWRP normally. ("fastboot boot", I have not tried installing it to recovery.)

**Comment by smurfix** [comment]
One possible cause is indeed that I also updated the firmware. Running stock 0110 now. @wonderfullyrich I'd recommend updating to that. No sense debugging the problem if it's solved with current firmware.

**Comment by wonderfullyrich** [comment]
That was it. Firmware updated to the latest and twrp now boot. Many thanks!

-------- Original Message --------

**Comment by sooorajjj** [comment]
Maybe new kernel changes or updates had dependencies in Bootloader . I can see panel related changes in FP3-REL-2.A.0105-20191217.132527 .

**Comment by gscout** [comment]
I confirm I had exactly the same problem with an non updated FP3, and after doing the update to stock 0110 like you guys proposed, the problem was gone
