### ISSUE TITLE
Does the Android 12 release support data encryption?

### ISSUE THREAD

**Issue by bege10** [chaosmaster/android_device_fairphone_fp3#5]
Hello,
the official TWRP is in the Android 9 branch and does not support data encryption if Android 12 is installed.
Does the Android 12 release in this repo support data encryption?

**Comment by chaosmaster** [comment]
The release I just uploaded now should be able to decrypt FPOS13, LOS20 and /e/ 1.13.

**Comment by bege10** [comment]
> The release I just uploaded now should be able to decrypt FPOS13, LOS20 and /e/ 1.13.

This is amazing! I will try with /e/OS 1.13.
